# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 151a9cae61965c0388d8a0c3b833e11a125d600b385ed4ff55f4261db0964829faf122a0efc97176744757cffae620f48e5204987b121689b108536dfad15176

test:
  secret_key_base: ec8a797cfaae6d4635c2eb7965841e7b0eb9124db6806b241f817c4fcfd5749549121e7cab2a7c7c46e4993c9e84dae9aba39d8162965d27b1b0daa3fdacde8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
